### ISSUE TITLE
Error: socket hang up

### ISSUE THREAD

**Issue by kaiwen1811** [HuangXiZhou/DyttReptitle#1]
你好，我在爬取详情页下载链接的时候报错了，不知道是不是请求过多，请问一下如何处理并发？

**Comment by kaiwen1811** [comment]
node版本是v8.9.0的

**Comment by HuangXiZhou** [comment]
本项目并没有做并发处理，电影天堂并未作出 ip 限定。电影天堂本身服务器也比较慢，所以经常出现请求超时的情况，应该加个超时判断再加个 `res.end` 就好了，非 bug 但欢迎 pr🙋🏻‍♂️🙋🏻‍♂️🙋🏻‍♂️
